# IZP - projekt 1 - Prace s textem 
# Soubor: Makefile
# Datum: Rijen 2016
# Autor: Gabriela Necasova 

# prekladac jazyka 
CC=gcc

# parametry prekladace 
CFLAGS=-std=c99 -Wall -Wextra -Werror

# nazev souboru 
PROJ=proj1

# pravidla 
all: $(PROJ).c
	$(CC) $(CFLAGS) $(PROJ).c -o $(PROJ)    

clean:
	rm $(PROJ)
